version: 2.1

orbs:
  node: circleci/node@7.1.0

jobs:
  bobby:
    docker:
      - image: circleci/node@7.1.0
    steps:
      - checkout
      - run: echo "A first hello"
  sally:
    docker:
      - image: circleci/node@7.1.0
    steps:
      - checkout
      - run: echo "Double Trouble"

workflows:
  version: 2.1
  bobby_sally:
    jobs:
      - bobby
      - sally
